#include <cassert>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>
#include "../crypto.h"
#include "../spake2.h"
#include "../qr.h"
#include "../receipt.h"
#include "../json.h"

static int failures = 0;
#define CHECK(cond, msg) do { if (!(cond)) { std::cerr << "FAIL: " << msg << "\n"; ++failures; } \
                              else { std::cout << "ok: " << msg << "\n"; } } while (0)

static void test_gcm_roundtrip() {
    auto key = crypto::random_vec(crypto::KEY_LEN);
    const char* msg = "hello bandrop, this is a secret payload";
    int pl = (int)std::strlen(msg);
    std::vector<unsigned char> out(crypto::NONCE_LEN + pl + crypto::TAG_LEN);
    int n = crypto::seal(key.data(), (const unsigned char*)msg, pl, nullptr, 0, out.data());
    CHECK(n > 0, "gcm seal");
    std::vector<unsigned char> dec(pl + 16);
    int d = crypto::open(key.data(), out.data(), n, nullptr, 0, dec.data());
    CHECK(d == pl && std::memcmp(dec.data(), msg, pl) == 0, "gcm open roundtrip");
}

static void test_gcm_tamper() {
    auto key = crypto::random_vec(crypto::KEY_LEN);
    const char* msg = "tamper me";
    int pl = (int)std::strlen(msg);
    std::vector<unsigned char> out(crypto::NONCE_LEN + pl + crypto::TAG_LEN);
    int n = crypto::seal(key.data(), (const unsigned char*)msg, pl, nullptr, 0, out.data());
    out[crypto::NONCE_LEN + 2] ^= 0x40; // flip a ciphertext bit
    std::vector<unsigned char> dec(pl + 16);
    int d = crypto::open(key.data(), out.data(), n, nullptr, 0, dec.data());
    CHECK(d == -1, "gcm rejects tampered ciphertext");
}

static void test_gcm_wrong_key() {
    auto key = crypto::random_vec(crypto::KEY_LEN);
    auto bad = crypto::random_vec(crypto::KEY_LEN);
    const char* msg = "x";
    std::vector<unsigned char> out(crypto::NONCE_LEN + 1 + crypto::TAG_LEN);
    int n = crypto::seal(key.data(), (const unsigned char*)msg, 1, nullptr, 0, out.data());
    std::vector<unsigned char> dec(32);
    CHECK(crypto::open(bad.data(), out.data(), n, nullptr, 0, dec.data()) == -1,
          "gcm rejects wrong key");
}

static void test_hkdf_deterministic() {
    unsigned char ikm[8] = {1,2,3,4,5,6,7,8};
    unsigned char salt[4] = {9,9,9,9};
    auto a = crypto::hkdf(ikm, 8, salt, 4, "info", 40);
    auto b = crypto::hkdf(ikm, 8, salt, 4, "info", 40);
    auto c = crypto::hkdf(ikm, 8, salt, 4, "other", 40);
    CHECK(a == b && a.size() == 40, "hkdf deterministic, right length");
    CHECK(a != c, "hkdf differs by info");
}

static void test_spake2_agreement() {
    auto salt = crypto::random_vec(crypto::SALT_LEN);
    Spake2 a(Spake2::Role::A, "473829", salt.data(), salt.size());
    Spake2 b(Spake2::Role::B, "473829", salt.data(), salt.size());
    auto sa = a.finish(b.public_share());
    auto sb = b.finish(a.public_share());
    CHECK(sa.key == sb.key && sa.key.size() == 32, "spake2 same session key");
    CHECK(a.verify_peer(sb.confirm), "spake2 A verifies B confirm");
    CHECK(b.verify_peer(sa.confirm), "spake2 B verifies A confirm");
}

static void test_spake2_wrong_pin() {
    auto salt = crypto::random_vec(crypto::SALT_LEN);
    Spake2 a(Spake2::Role::A, "111111", salt.data(), salt.size());
    Spake2 b(Spake2::Role::B, "222222", salt.data(), salt.size());
    auto sa = a.finish(b.public_share());
    auto sb = b.finish(a.public_share());
    CHECK(sa.key != sb.key, "spake2 wrong pin -> different keys");
    CHECK(!a.verify_peer(sb.confirm), "spake2 wrong pin -> A rejects");
    CHECK(!b.verify_peer(sa.confirm), "spake2 wrong pin -> B rejects");
}


// golden QR vectors (generated by the independent `qrcode` reference)
static const struct { const char* data; int v, ecl, mask; const char* bits; } QR_GOLDEN[] = {
    {"BANDROP", 2, 1, 3, "1111111011000111001111111100000101001010010100000110111010000010001010111011011101010001011001011101101110100000001010101110110000010001111011010000011111111010101010101111111000000001110000110000000010110111001101010010010111010000000110111011000101100101110010010010111010011110001110010001011011101001011011011011010001001010000011001101011010101001011011100101011001101101000110011010010111110000000010100110101111111101000000000110000111000101001111111011100111101011111100000101001011010001100110111010010001101111101101011101010100000001000101101110101000001000001111010000010010111101111011001111111010010000100000011"},
    {"http://192.168.1.5:8000/", 3, 1, 2, "1111111000010111000100111111110000010010001111010001000001101110101101110100100010111011011101010001011011010101110110111010110000011111001011101100000101110100001000010000011111111010101010101010111111100000000100100101000000000000101111100010000010101011111000010100101100111011100101000100001010101001111100000110000001011001001010101100110100100110111000100011000111010110001101001110100011011001010101101101101011000000100110001000110100001111010100101010001001001111111110001011110000100100001000010011101010110111011001011000010111110010100110010110101101111010110111010010101110100010001100001111101110000000011010001101110001111111111110010000000011101011100100000101001101010001000100101011101011011000101011111111110111010101001110100110100000101110101001111111011010110101000001000001001011011011001011111110111110110000000001100"},
    {"x", 1, 0, 0, "111111100101101111111100000100111001000001101110101101101011101101110100101001011101101110100010101011101100000100000101000001111111101010101111111000000001101100000000111011111111011000100111011010100001000110011101111000100010001000011011000001000110111111101100101010100000000001101010101001111111101101011101111100000101001110111000101110101101011101101101110100000001000110101110101010100010001100000101000001000110111111101010101010111"},
};

static void test_qr_golden() {
    for (auto& g : QR_GOLDEN) {
        auto m = qr::encode_fixed(g.data, g.v, g.ecl, g.mask);
        std::string bits;
        for (auto& row : m) for (bool b : row) bits += (b ? '1' : '0');
        CHECK(bits == g.bits, std::string("qr golden ") + g.data);
    }
    // encode() must fit a URL and produce a square finder-bearing matrix.
    auto u = qr::encode("http://192.168.1.42:8000/", qr::M);
    bool ok = !u.empty() && u.size() == u[0].size();
    // top-left finder ring present.
    if (ok) ok = u[0][0] && u[0][6] && !u[1][1] && u[2][2];
    CHECK(ok, "qr encode() URL produces valid matrix");
}


static void test_json_roundtrip() {
    json::Value o;
    bool ok = json::parse("{\"a\":1,\"b\":[true,\"x\",null],\"c\":{\"d\":-3.5}}", o);
    CHECK(ok && o.type == json::Value::Obj, "json parse object");
    const json::Value* a = o.find("a");
    CHECK(a && a->num == 1, "json number");
    const json::Value* b = o.find("b");
    CHECK(b && b->type == json::Value::Arr && b->arr->size() == 3, "json array");
}

static void test_receipt_sign_verify() {
    identity::Key k = identity::load_or_create();
    receipt::Receipt r;
    r.timestamp = 1700000000;
    r.files.push_back({"a.txt", 5, crypto::sha256((const unsigned char*)"hello", 5)});
    r.files.push_back({"sub/b.bin", 3, crypto::sha256((const unsigned char*)"abc", 3)});
    receipt::sign(r, k);
    CHECK(receipt::verify(r), "receipt verifies after signing");

    std::string js = receipt::to_json(r);
    receipt::Receipt r2;
    CHECK(receipt::from_json(js, r2), "receipt json round-trip parses");
    CHECK(receipt::verify(r2), "receipt verifies after json round-trip");

    // Tamper: change a recorded size -> signature must fail.
    r2.files[0].size = 6;
    CHECK(!receipt::verify(r2), "receipt rejects tampered size");
}

int main() {
    test_gcm_roundtrip();
    test_gcm_tamper();
    test_gcm_wrong_key();
    test_hkdf_deterministic();
    test_spake2_agreement();
    test_spake2_wrong_pin();
    test_qr_golden();
    test_json_roundtrip();
    test_receipt_sign_verify();
    std::cout << (failures ? "\nSOME TESTS FAILED\n" : "\nALL TESTS PASSED\n");
    return failures ? 1 : 0;
}
